/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.com.tdea;

import java.awt.Graphics;
import java.awt.Image;
import java.sql.Connection;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author nmejia
 */
public class JF_inicio extends javax.swing.JFrame {

    private Validador validador;

    /**
     * Creates new form JF_inicio
     */
    public JF_inicio(Validador validador) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.validador = validador;
        lblClub.setText(validador.getClub().toString());
        btnGroupRegistrar.add(jrVentana1Asociado);
        btnGroupRegistrar.add(jrVentana1Socio);

    }

    public JF_inicio() {
        initComponents();
        this.setLocationRelativeTo(null);
        if (validador == null) {
            validador = new Validador();
            System.out.println("el club esta en " + validador);

        }
        Connection con = Conexion_BD.getConexion();
//        validador.CantidadSociosVIP();

        lblClub.setText(validador.getClub().toString());
        jtaMostrar.setEditable(false);
        btnGroupRegistrar.add(jrVentana1Asociado);
        btnGroupRegistrar.add(jrVentana1Socio);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSuscripcion = new javax.swing.JLabel();
        btnGroupRegistrar = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lblClub = new javax.swing.JLabel();
        jPanelSocios = new javax.swing.JPanel();
        txtNombre = new javax.swing.JTextField();
        lblNombre1 = new javax.swing.JLabel();
        lblCedula = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        lblPanelSocio = new javax.swing.JLabel();
        jcbSuscripcion = new javax.swing.JComboBox<>();
        btnRegistrarSocio = new javax.swing.JButton();
        btnBuscarSocio = new javax.swing.JButton();
        btnEliminarSocio = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnAumentarFodos = new javax.swing.JButton();
        lblFondosSocio = new javax.swing.JLabel();
        txtFondosSocio = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel_Busqueda = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaMostrar = new javax.swing.JTextArea();
        lblResultadosBusqueda = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        txtNomAutorizadas = new javax.swing.JTextField();
        lblNomPersonasAutorizadas = new javax.swing.JLabel();
        lblCedulaPersonasAutorizadas = new javax.swing.JLabel();
        txtCedulaPersonasAutorizadas = new javax.swing.JTextField();
        btnRegistrarPersonaAutorizada = new javax.swing.JButton();
        btnBuscarPersonaAutorizada = new javax.swing.JButton();
        btnEliminarPersonaAutorizada = new javax.swing.JButton();
        JblPersonasAutorizadas = new javax.swing.JLabel();
        btnCargarAsociados = new javax.swing.JButton();
        jpRegistrarConsumo = new javax.swing.JPanel();
        lblCedulaCliente = new javax.swing.JLabel();
        txtCedulaCliente = new javax.swing.JTextField();
        btnEliminarFactura = new javax.swing.JButton();
        JblRegistrarConsumo = new javax.swing.JLabel();
        btnPagarFactura = new javax.swing.JButton();
        txtnumfactura = new javax.swing.JTextField();
        lblnumfactura = new javax.swing.JLabel();
        lblCedulaPautorizada = new javax.swing.JLabel();
        txtcPersonaAutorizada = new javax.swing.JTextField();
        btnBuscarFactura = new javax.swing.JButton();
        btnHabilitarMenu = new javax.swing.JButton();
        jrVentana1Socio = new javax.swing.JRadioButton();
        jrVentana1Asociado = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();

        lblSuscripcion.setText("Tipo Suscripcion");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setToolTipText("");

        lblClub.setFont(new java.awt.Font("Arial", 2, 36)); // NOI18N
        lblClub.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClub.setText("zzz");
        lblClub.setToolTipText("");

        jPanelSocios.setBackground(new java.awt.Color(102, 102, 102));
        jPanelSocios.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        lblNombre1.setText("Nombre");

        lblCedula.setText("Cedula");

        lblPanelSocio.setBackground(new java.awt.Color(255, 255, 255));
        lblPanelSocio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblPanelSocio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblPanelSocio.setText("Suscripcion");

        jcbSuscripcion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "VIP", "REGULAR" }));
        jcbSuscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbSuscripcionActionPerformed(evt);
            }
        });

        btnRegistrarSocio.setText("Registrar");
        btnRegistrarSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarSocioActionPerformed(evt);
            }
        });

        btnBuscarSocio.setText("Buscar");
        btnBuscarSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarSocioActionPerformed(evt);
            }
        });

        btnEliminarSocio.setText("Eliminar");
        btnEliminarSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarSocioActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SOCIOS");

        btnAumentarFodos.setText("Fondos");
        btnAumentarFodos.setToolTipText("");
        btnAumentarFodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAumentarFodosActionPerformed(evt);
            }
        });

        lblFondosSocio.setText("Fondos");

        txtFondosSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFondosSocioActionPerformed(evt);
            }
        });

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelSociosLayout = new javax.swing.GroupLayout(jPanelSocios);
        jPanelSocios.setLayout(jPanelSociosLayout);
        jPanelSociosLayout.setHorizontalGroup(
            jPanelSociosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSociosLayout.createSequentialGroup()
                .addGroup(jPanelSociosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSociosLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelSociosLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanelSociosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelSociosLayout.createSequentialGroup()
                                .addComponent(lblPanelSocio, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcbSuscripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelSociosLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(jPanelSociosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblFondosSocio, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanelSociosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelSociosLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanelSociosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                                            .addComponent(txtFondosSocio, javax.swing.GroupLayout.Alignment.LEADING)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSociosLayout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelSociosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnRegistrarSocio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                            .addComponent(btnEliminarSocio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAumentarFodos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBuscarSocio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSociosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(49, 49, 49))
        );
        jPanelSociosLayout.setVerticalGroup(
            jPanelSociosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSociosLayout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(jPanelSociosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSociosLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelSociosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPanelSocio)
                            .addComponent(jcbSuscripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelSociosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelSociosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblFondosSocio, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSociosLayout.createSequentialGroup()
                        .addComponent(btnBuscarSocio)
                        .addGap(9, 9, 9)
                        .addComponent(btnRegistrarSocio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminarSocio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelSociosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAumentarFodos)
                            .addComponent(txtFondosSocio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(11, 11, 11))))
        );

        jPanel_Busqueda.setBackground(new java.awt.Color(102, 102, 102));
        jPanel_Busqueda.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jtaMostrar.setBackground(new java.awt.Color(204, 204, 204));
        jtaMostrar.setColumns(20);
        jtaMostrar.setRows(5);
        jScrollPane1.setViewportView(jtaMostrar);

        lblResultadosBusqueda.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        lblResultadosBusqueda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblResultadosBusqueda.setText("RESULTADOS DE BUSQUEDA");

        javax.swing.GroupLayout jPanel_BusquedaLayout = new javax.swing.GroupLayout(jPanel_Busqueda);
        jPanel_Busqueda.setLayout(jPanel_BusquedaLayout);
        jPanel_BusquedaLayout.setHorizontalGroup(
            jPanel_BusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_BusquedaLayout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addGroup(jPanel_BusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblResultadosBusqueda)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 50, Short.MAX_VALUE))
        );
        jPanel_BusquedaLayout.setVerticalGroup(
            jPanel_BusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_BusquedaLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblResultadosBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtNomAutorizadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomAutorizadasActionPerformed(evt);
            }
        });

        lblNomPersonasAutorizadas.setText("Nombre");

        lblCedulaPersonasAutorizadas.setText("Cedula");

        btnRegistrarPersonaAutorizada.setText("Registrar");
        btnRegistrarPersonaAutorizada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarPersonaAutorizadaActionPerformed(evt);
            }
        });

        btnBuscarPersonaAutorizada.setText("Buscar");
        btnBuscarPersonaAutorizada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPersonaAutorizadaActionPerformed(evt);
            }
        });

        btnEliminarPersonaAutorizada.setText("Eliminar");
        btnEliminarPersonaAutorizada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarPersonaAutorizadaActionPerformed(evt);
            }
        });

        JblPersonasAutorizadas.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        JblPersonasAutorizadas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JblPersonasAutorizadas.setText("<html><CENTER>PERSONAS<p>AUTORIZADAS</CENTER><html>");

        btnCargarAsociados.setIcon(new ImageIcon("./Imagenes/cargar.png"));
        btnCargarAsociados.setText("Importar");
        btnCargarAsociados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarAsociadosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblNomPersonasAutorizadas, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCedulaPersonasAutorizadas, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNomAutorizadas, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCedulaPersonasAutorizadas, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnEliminarPersonaAutorizada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBuscarPersonaAutorizada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRegistrarPersonaAutorizada, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                            .addComponent(btnCargarAsociados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(JblPersonasAutorizadas, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JblPersonasAutorizadas, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnRegistrarPersonaAutorizada)
                        .addGap(4, 4, 4)
                        .addComponent(btnBuscarPersonaAutorizada)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminarPersonaAutorizada))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCedulaPersonasAutorizadas, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCedulaPersonasAutorizadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNomPersonasAutorizadas, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNomAutorizadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCargarAsociados, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );

        jpRegistrarConsumo.setBackground(new java.awt.Color(102, 102, 102));
        jpRegistrarConsumo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblCedulaCliente.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblCedulaCliente.setText("Cedula Socio");

        btnEliminarFactura.setText("Eliminar");
        btnEliminarFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarFacturaActionPerformed(evt);
            }
        });

        JblRegistrarConsumo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        JblRegistrarConsumo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JblRegistrarConsumo.setText("CONSUMOS");

        btnPagarFactura.setText("Pagar");
        btnPagarFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagarFacturaActionPerformed(evt);
            }
        });

        lblnumfactura.setText("Numero Factura");

        lblCedulaPautorizada.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblCedulaPautorizada.setText("Cedula Asociado");

        btnBuscarFactura.setText("Ver Facturas");
        btnBuscarFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarFacturaActionPerformed(evt);
            }
        });

        btnHabilitarMenu.setBackground(new java.awt.Color(0, 102, 102));
        btnHabilitarMenu.setFont(new java.awt.Font("Book Antiqua", 1, 24)); // NOI18N
        btnHabilitarMenu.setText("MENU");
        btnHabilitarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHabilitarMenuActionPerformed(evt);
            }
        });

        jrVentana1Socio.setText("Socio");

        jrVentana1Asociado.setText("Asociado");

        jLabel2.setFont(new java.awt.Font("Broadway", 0, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Ingresar");

        javax.swing.GroupLayout jpRegistrarConsumoLayout = new javax.swing.GroupLayout(jpRegistrarConsumo);
        jpRegistrarConsumo.setLayout(jpRegistrarConsumoLayout);
        jpRegistrarConsumoLayout.setHorizontalGroup(
            jpRegistrarConsumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpRegistrarConsumoLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnHabilitarMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpRegistrarConsumoLayout.createSequentialGroup()
                .addGroup(jpRegistrarConsumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpRegistrarConsumoLayout.createSequentialGroup()
                        .addGroup(jpRegistrarConsumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpRegistrarConsumoLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jpRegistrarConsumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpRegistrarConsumoLayout.createSequentialGroup()
                                        .addComponent(lblCedulaPautorizada, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtcPersonaAutorizada, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jpRegistrarConsumoLayout.createSequentialGroup()
                                        .addGroup(jpRegistrarConsumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblCedulaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblnumfactura))
                                        .addGap(18, 18, 18)
                                        .addGroup(jpRegistrarConsumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtnumfactura, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtCedulaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jpRegistrarConsumoLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(JblRegistrarConsumo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jrVentana1Socio)))
                        .addGroup(jpRegistrarConsumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpRegistrarConsumoLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jrVentana1Asociado))
                            .addGroup(jpRegistrarConsumoLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jpRegistrarConsumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnEliminarFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnBuscarFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpRegistrarConsumoLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPagarFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jpRegistrarConsumoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator2)))
                .addContainerGap())
        );
        jpRegistrarConsumoLayout.setVerticalGroup(
            jpRegistrarConsumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpRegistrarConsumoLayout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addGroup(jpRegistrarConsumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHabilitarMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(jpRegistrarConsumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrVentana1Socio)
                    .addComponent(jrVentana1Asociado)
                    .addComponent(JblRegistrarConsumo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jpRegistrarConsumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpRegistrarConsumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtnumfactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnPagarFactura))
                    .addComponent(lblnumfactura))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpRegistrarConsumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCedulaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCedulaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarFactura))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpRegistrarConsumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcPersonaAutorizada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCedulaPautorizada, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarFactura))
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanelSocios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel_Busqueda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jpRegistrarConsumo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(lblClub, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblClub, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpRegistrarConsumo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelSocios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel_Busqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarPersonaAutorizadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarPersonaAutorizadaActionPerformed
        // TODO add your handling code here:
        validador.eliminarPersonaAutorizada(txtCedula.getText(), txtCedulaPersonasAutorizadas.getText());
    }//GEN-LAST:event_btnEliminarPersonaAutorizadaActionPerformed

    private void btnBuscarPersonaAutorizadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPersonaAutorizadaActionPerformed
        // TODO add your handling code here:
        jtaMostrar.setText(validador.MostrarPersonaAutorizada(txtCedulaPersonasAutorizadas.getText(), txtCedula.getText()));

    }//GEN-LAST:event_btnBuscarPersonaAutorizadaActionPerformed

    private void btnRegistrarPersonaAutorizadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarPersonaAutorizadaActionPerformed
        // TODO add your handling code here:
        validador.registrarPersonaAutorizada(txtNomAutorizadas.getText(), txtCedulaPersonasAutorizadas.getText(), txtCedula.getText());

    }//GEN-LAST:event_btnRegistrarPersonaAutorizadaActionPerformed

    private void txtNomAutorizadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomAutorizadasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomAutorizadasActionPerformed

    private void btnEliminarSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarSocioActionPerformed

        //validador.EliminarSocio(txtCedula.getText());
        validador.EliminarSocioBD(txtCedula.getText());
    }//GEN-LAST:event_btnEliminarSocioActionPerformed

    private void btnBuscarSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarSocioActionPerformed
        // TODO add your handling code here:
        try {

            jtaMostrar.setText(validador.validarMostrarSocio(txtCedula.getText()));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }

    }//GEN-LAST:event_btnBuscarSocioActionPerformed

    private void btnRegistrarSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarSocioActionPerformed
        // TODO add your handling code here:
        validador.registrarSocio(txtCedula.getText(), jcbSuscripcion.getSelectedItem().toString(), txtNombre.getText());
        txtCedula.setText("");
        txtNombre.setText("");
    }//GEN-LAST:event_btnRegistrarSocioActionPerformed

    private void jcbSuscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbSuscripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbSuscripcionActionPerformed

    private void btnCargarAsociadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarAsociadosActionPerformed
        // TODO add your handling code here:

        try {
            validador.CargarPersonaAutorizada();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }


    }//GEN-LAST:event_btnCargarAsociadosActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed

    }//GEN-LAST:event_txtNombreActionPerformed

    private void btnAumentarFodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAumentarFodosActionPerformed

        //validador.aumentarRecursos(txtCedula.getText(), txtFondosSocio.getText());
        validador.aumentarRecursosSocioBD(txtCedula.getText(), txtFondosSocio.getText());
    }//GEN-LAST:event_btnAumentarFodosActionPerformed

    private void txtFondosSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFondosSocioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFondosSocioActionPerformed

    private void btnPagarFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarFacturaActionPerformed
        // TODO add your handling code here:

        try {
            if (jrVentana1Socio.isSelected()) {
                validador.pagarfacturaS(txtCedulaCliente.getText(), txtnumfactura.getText());
            } else if (jrVentana1Asociado.isSelected()) {
                validador.pagarConsumoAsociados(txtCedulaCliente.getText(), txtcPersonaAutorizada.getText(), txtnumfactura.getText());

            } else {
                JOptionPane.showMessageDialog(null, "debe seleccionar sicio a asociado de quien necesita ver las facturas ");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }


    }//GEN-LAST:event_btnPagarFacturaActionPerformed

    private void btnEliminarFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarFacturaActionPerformed
        // TODO add your handling code here:

        try {
            if (jrVentana1Socio.isSelected()) {
                validador.eliminarfacturaS(txtCedulaCliente.getText(), txtnumfactura.getText());
            } else if (jrVentana1Asociado.isSelected()) {
                validador.eliminarFacturaAsociado(txtCedulaCliente.getText(), txtcPersonaAutorizada.getText(), txtnumfactura.getText());

            } else {
                JOptionPane.showMessageDialog(null, "debe seleccionar sicio a asociado de quien necesita ver las facturas ");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }


    }//GEN-LAST:event_btnEliminarFacturaActionPerformed

    private void btnBuscarFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarFacturaActionPerformed
        // TODO add your handling code here:
        //validador.BuscarfacturaSocio(txtCedulaCliente.getText());
        try {
            if (jrVentana1Socio.isSelected()) {
                jtaMostrar.setText(validador.BuscarfacturaSocio(txtCedulaCliente.getText()));
            } else if (jrVentana1Asociado.isSelected()) {
                jtaMostrar.setText(validador.mostrarConsumoAsociado(txtCedulaCliente.getText(), txtcPersonaAutorizada.getText()));

            } else {
                JOptionPane.showMessageDialog(null, "debe seleccionar sicio a asociado de quien necesita ver las facturas ");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }

    }//GEN-LAST:event_btnBuscarFacturaActionPerformed

    private void btnHabilitarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHabilitarMenuActionPerformed
        // TODO add your handling code here:
        JF_consumo ventana2 = new JF_consumo(validador);
        ventana2.show();
        this.setVisible(false);

    }//GEN-LAST:event_btnHabilitarMenuActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
//        validador.Buscarsocio(Integer.parseInt(txtCedula.getText()));
        validador.registrarSocioBD(txtCedula.getText(), jcbSuscripcion.getSelectedItem().toString(), txtNombre.getText());
        txtCedula.setText("");
        txtNombre.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new JF_inicio().setVisible(true);

            }

        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JblPersonasAutorizadas;
    private javax.swing.JLabel JblRegistrarConsumo;
    private javax.swing.JButton btnAumentarFodos;
    private javax.swing.JButton btnBuscarFactura;
    private javax.swing.JButton btnBuscarPersonaAutorizada;
    private javax.swing.JButton btnBuscarSocio;
    private javax.swing.JButton btnCargarAsociados;
    private javax.swing.JButton btnEliminarFactura;
    private javax.swing.JButton btnEliminarPersonaAutorizada;
    private javax.swing.JButton btnEliminarSocio;
    private javax.swing.ButtonGroup btnGroupRegistrar;
    private javax.swing.JButton btnHabilitarMenu;
    private javax.swing.JButton btnPagarFactura;
    private javax.swing.JButton btnRegistrarPersonaAutorizada;
    private javax.swing.JButton btnRegistrarSocio;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelSocios;
    private javax.swing.JPanel jPanel_Busqueda;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JComboBox<String> jcbSuscripcion;
    private javax.swing.JPanel jpRegistrarConsumo;
    private javax.swing.JRadioButton jrVentana1Asociado;
    private javax.swing.JRadioButton jrVentana1Socio;
    private javax.swing.JTextArea jtaMostrar;
    private javax.swing.JLabel lblCedula;
    private javax.swing.JLabel lblCedulaCliente;
    private javax.swing.JLabel lblCedulaPautorizada;
    private javax.swing.JLabel lblCedulaPersonasAutorizadas;
    private javax.swing.JLabel lblClub;
    private javax.swing.JLabel lblFondosSocio;
    private javax.swing.JLabel lblNomPersonasAutorizadas;
    private javax.swing.JLabel lblNombre1;
    private javax.swing.JLabel lblPanelSocio;
    private javax.swing.JLabel lblResultadosBusqueda;
    private javax.swing.JLabel lblSuscripcion;
    private javax.swing.JLabel lblnumfactura;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtCedulaCliente;
    private javax.swing.JTextField txtCedulaPersonasAutorizadas;
    private javax.swing.JTextField txtFondosSocio;
    private javax.swing.JTextField txtNomAutorizadas;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtcPersonaAutorizada;
    private javax.swing.JTextField txtnumfactura;
    // End of variables declaration//GEN-END:variables
}
